### ISSUE TITLE
Max stack size exceeded error on pumping lot of data from controller to the view

### ISSUE THREAD

**Issue by chetanankola** [YahooArchive/mojito#133] opened 2012-04-14 01:28 UTC
I am performing a refreshView on one of the mojits which fetches (not really a lot) information for eg:facebook friends.
And this is the error I get.

Is this a bug? Or is there a way to send information to the view in chunks or something?

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
RangeError: Maximum call stack size exceeded
    at Function.APPLY_OVERFLOW (native)
    at Object.metaMerge (/usr/lib/node_modules/mojito/lib/app/autoload/util.common.js:132:41)
    at Object.metaMerge (/usr/lib/node_modules/mojito/lib/app/autoload/util.common.js:138:55)
    at Object.metaMerge (/usr/lib/node_modules/mojito/lib/app/autoload/util.common.js:138:55)
    at Object._updateBuffer (/usr/lib/node_modules/mojito/lib/mojits/DaliProxy/controller.server.js:33:43)
    at Object.flush (/usr/lib/node_modules/mojito/lib/mojits/DaliProxy/controller.server.js:49:22)
    at RenderEventEmitter.<anonymous> (/usr/lib/node_modules/mojito/lib/app/addons/view-engines/mu.server.js:47:33)
    at RenderEventEmitter.emit (events.js:67:17)
    at RenderEventEmitter.emitChunks (/usr/lib/node_modules/mojito/lib/app/libs/Mulib/mu/compiler.js:112:18)
    at RenderEventEmitter.write (/usr/lib/node_modules/mojito/lib/app/libs/Mulib/mu/compiler.js:86:14)

This can be easily replicated say by repeating the mustache tags in the view which contains a reasonably sized chunk of data.

**Comment by isao** [comment] 2012-04-18 21:21
yes the team is working on a fix to this ASAP...

It would be really helpful if you could post a mojito app test case too...

**Comment by mojit0** [comment] 2012-05-30 18:06
I believe a fix for this is now awaiting final review. It's effectively a duplicate of issue #12.

**Closed as completed by mojit0** 2012-05-30 18:06 UTC
Labels: bug
