### ISSUE TITLE
Compatibility with node.js on windows

### ISSUE THREAD

**Issue by focuzz8** [YahooArchive/mojito#264] opened 2012-07-12 16:35 UTC
Since there is no more dependency on *nix (yui test migrated to 0.7.4) is there possible to make run of Mojito on windows? I spend some time, but found that there is problem with loader - in mojito/source/lib/index.js - YUI instance doesn't contain any standard modules, that should be loaded after init. Probably problem is in nodejs-yui, but I'm not sure.

**Comment by rwaldura** [comment] 2012-07-12 17:27
Hi @focuzz:
Indeed I don't think we ever tested that, seeing how we use mostly Macs and Linux boxen. 
Would you be able to narrow it down further? What seems to be the problem in nodejs-yui?

**Comment by focuzz8** [comment] 2012-07-12 18:10
Yes, I will try to find root of problem, today some hours later. It seems (as I remember) like yui loader can't find modules that are required to start mojito... I'll dig it a bit and will write or more deep description, or solution (if i'll find any)

**Comment by rwaldura** [comment] 2012-07-12 18:15
Yeah might just be a silly path issue.

**Comment by focuzz8** [comment] 2012-07-16 16:49
I've made some fixes, so mojito starts and renders mojits (there is problem with binders). So situation is better and it don't passes only 2 tests. You can see changes here https://github.com/focuzz/mojito/tree/win-compat
I'm not doing pull request, because multi os support slightly broke cody prettiness, because
- path.sep appeared only in node 0.8 and I'm using handmade function to get separator
- there is a lot of places where path.combine have used to generates url, what brakes on windows
- robably I've found not all places where fixes needed
  So can anybody review it and tell me whether I'm doing it in right way, or I should correct something?
  Thank you.

**Comment by rwaldura** [comment] 2012-07-18 19:55
Thanks Alexey. This is starting to sound like a bigger item than anticipated, does it not?

We're not currently setup to run our automated tests on Windows, so it's going hard for us to validate your fixes (Of course, we could validate they don't break MacOS/Linux, but that's only a negative test...)

Few people have asked for Windows support, it hasn't been a priority for us at this point.

**Comment by focuzz8** [comment] 2012-07-18 22:18
Well, I'm using them all (win + lin + mac) for different tasks, so it's not a critical problem for me right now. I understand about priority, so, I'll try to fix remaining issues in future(probably week or two). And after I can try to maintain this windows compatible branch, and merge your releases - and probably community will grow by time. If it will be interesting to anyone - probably it can be unofficial windows compatible branch or something like this in future (hope).

**Comment by rwaldura** [comment] 2012-07-18 22:22
Sounds like a good compromise. Thanks!
Let's keep this issue open to track this feature.

**Comment by Merlin8000** [comment] 2012-08-21 13:14
I'd like to chime in and add to the few that would like to see windows compatibility.  While I'm not actively developing in mojito now, the lack of windows compatibility was absolutely the first thing that really took the wind out of my sails when I was first getting started with it.

I've been keeping a watchful eye on this project because I see a lot of promise, and this is definitely one of the things that I would like to see.

**Comment by rwaldura** [comment] 2012-08-21 15:13
Thanks @Merlin8000 for your vote.
Part of the problem is that we're not setup for running (testing) Mojito on Windows. 
Travis doesn't help, as it doesn't support Windows either. Any ideas?
http://about.travis-ci.org/docs/user/ci-environment/

**Comment by Merlin8000** [comment] 2012-08-21 21:06
@rwaldura As I understand it, it's common for unit testing frameworks like that to have difficulties with Windows.  I honestly don't see a comparable solution, I think that the next-best QA tool may be the bug tracker (as stated here, that's a pretty far cry from a build/testing framework).

So really I can only say that I hope that things improve.  I understand the current state of things and will continue to keep a watchful eye on this project.

If the number of requests for support is a factor in setting priorities then I appreciate that you've included my vote.

**Comment by rwaldura** [comment] 2012-08-21 22:42
We certainly didn't try to break Windows compatibility on purpose. :(
@focuzz was looking into what's currently broken, and I was under the impression that, with a good PR, we could solve this. 
@Merlin8000 would you be willing to help him?

**Comment by Merlin8000** [comment] 2012-08-22 18:59
I'd at least be willing to run tests if the instructions are well written.

**Comment by focuzz8** [comment] 2012-08-22 20:23
```
npm install mojito@0.4.2
node_modules\.bin\mojito.cmd test
```

but it seems like this don't work because of path differences on *nix and windows

**Comment by rsaiprasad** [comment] 2012-08-24 03:56
I strongly believe that windows compatibility is a must esp for a app framework like this. Most of the developers esp the less experienced one out there are on Windows. And for the framework to be adopted more, its a must that these guys can use it easily with out pain. Infact this is should be one of the high priority bugs to be resolved.

**Comment by rsaiprasad** [comment] 2012-08-24 08:42
Thanks @focuzz your fixes work like charm. I am able to run mojito on windows now. Would let you know incase I find any bugs / issues.

**Comment by rwaldura** [comment] 2012-08-24 17:31
Great to hear! 
Any ideas on how we could get this tested? Is there some sort of Travis-like for Windows out there? How do the Node guys test their stuff?

**Comment by add0n** [comment] 2012-08-24 18:18
This is a particular pain point of mine so I really appreciate the work you've done to make Mojito work on Windows. The main thing preventing us from merging this is our concern about being able to have a CI environment that can keep the Windows port tested, as stated by rwaldura above. Please let us know if there is a testing framework for Windows like Travis.

**Comment by mridgway** [comment] 2012-08-24 19:15
+1. I know Travis has Windows testing on their radar, but no ETA for support. We may just have to wait for them to get our CI on Windows up and running, but I don't think it should prevent us from accepting PRs that make Windows work as long as they don't raise regressions on our current CI.

**Comment by focuzz8** [comment] 2012-08-24 21:07
it seems like here we can find ci services for node https://github.com/joyent/node/wiki/Build-Servers
bamboo is free for open source projects http://www.atlassian.com/software/bamboo/pricing - and it was written that windows is supported too

**Comment by rwaldura** [comment] 2012-09-06 05:54
Okay, can we claim we're done here?
Reopen if you disagree.

**Comment by mridgway** [comment] 2012-09-06 06:44
The PR hasn't been merged, and there is still much left to be done if we're going to properly support Windows. As such, I think this should be left open.

**Closed as completed** 2013-05-17 00:57 UTC
