### ISSUE TITLE
[bz5646042] `mojito start` fails in 0.3.27

### ISSUE THREAD

**Issue by isao** [YahooArchive/mojito#223] opened 2012-06-21 18:50 UTC
to reproduce:
- upgrade to mojito 0.3.27
- `mojito start`
- error for an app that worked pre 0.3.27, but has YUI3.4.x/Jsdom dependencies:
  
  ```
  ✖ There was an error starting the application:
  ✖ Cannot read property 'documentElement' of null
  TypeError: Cannot read property 'documentElement' of null
  at Object.fn (/Users/isao/Repos/mojito/myfork/source/node_modules/yui/dom-base/dom-base-min.js:7:50)
  ```

**Comment by mridgway** [comment] 2012-08-06 04:33
Is this relevant any more? Looks like this can be closed since we are recommending upgrading to later versions.

**Comment by FabianFrank** [comment] 2012-08-06 05:04
I also think it can be closed.

**Comment by ramses0** [comment] 2012-08-14 04:17
$ mojito version
path.existsSync is now called `fs.existsSync`.
Version of mojito is 0.3.30

...following: http://developer.yahoo.com/cocktails/mojito/docs/getting_started/mojito_getting_started_tutorial.html#make-the-application

$ mojito test app .path.existsSync is now called `fs.existsSync`.
[warn] undefined: overriding application config value: env
[WARN] MojitoServer: your mojit "HelloMojit" has a server affinity and these client-related deps: node-base, node-core, dom-core, dom-base, node-event, node-pluginhost, node-screen, dom-screen, dom-style, dom-style, node-style
[WARN] MojitoServer: Mojito may be unable to start, unless you have provided server-side DOM/host-object suppport

...snip...

timers.js:103
            if (!process.listeners('uncaughtException').length) throw e;
                                                                      ^
TypeError: Cannot read property 'documentElement' of null
    at Object.YUI.add.requires [as fn] (/usr/local/lib/node_modules/mojito/node_modules/yui/dom-base/dom-base-min.js:7:50)

...tutorial or mojito is broken.

**Comment by rwaldura** [comment] 2012-08-14 15:40
@ramses0 is your code nothing more than the tutorial app? what's in your HelloMojit?
@zhouyaoji

**Comment by ramses0** [comment] 2012-08-14 20:32
Yep, this is "base case" stupidly following the tutorial.  I tried changing controller.server.js to controller.client.js to maybe adjust the "affinity" (?) but it gave different error messages which I am not familiar enough with mojito / node to figure out off the top of my head.

Quickstart worked: http://developer.yahoo.com/cocktails/mojito/docs/quickstart/  but the "HelloWorld" has not.  Literally just `mojito create app ; mojito create mojit ; mojito start` as suggested by the tutorial.

This is with latest npm / node and the 0.3.30 mojito freshly downloaded.  npm install mojito -g ... and copy/paste all the config stuff from the tutorial examples.  Server starts after tweaking, but gives a different error message which I don't have on this computer. Shouldn't be hard to reproduce.

**Comment by rwaldura** [comment] 2012-08-14 21:11
Mmmh wow okay. @jenny could we look into this? I'm not going to be able to get to this today, sorry.

**Comment by rwaldura** [comment] 2012-08-14 21:16
I'm closing this ticket in favor of #387 -- let's work on this over there.

**Closed as completed by rwaldura** 2012-08-14 21:16 UTC

**Comment by idearat** [comment] 2012-08-14 21:28
I think closing is the right answer for 0.3.27 bugs. It turned out to be an unstable release for a lot of consumers. Focusing on 0.3.30+ and 0.4+ is the best answer.
